apiVersion: v1
kind: Service
metadata:
  name: message-api
spec:
  selector:
    app: message-api
  ports:
    - port: 8081
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-api
  template:
    metadata:
      labels:
        app: message-api
    spec:
      containers:
        - name: app
          image: ctrlouis/message-api:1.1
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/dev
          imagePullPolicy: Always