apiVersion: v1
kind: Service
metadata:
  name: message-client
spec:
  selector:
    app: message-client
  ports:
    - port: 8080
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-client
spec:
  replicas: 5
  selector:
    matchLabels:
      app: message-client
  template:
    metadata:
      labels:
        app: message-client
    spec:
      containers:
        - name: app
          image: ctrlouis/message-client:1.0
          ports:
            - containerPort: 80
          imagePullPolicy: Always