apiVersion: v1
kind: Service
metadata:
  name: message-api
spec:
  selector:
    app: message-api
  ports:
    - port: 8081
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-api
spec:
  replicas: 5
  selector:
    matchLabels:
      app: message-api
  template:
    metadata:
      labels:
        app: message-api
    spec:
      containers:
        - name: app
          image: ctrlouis/message-api:1.2
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/dev
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
          imagePullPolicy: Always